### ISSUE TITLE
_getWatch is not a function

### ISSUE THREAD

**Issue by mkoehlerJjk** [react-hook-form/devtools#105]
I have been using the devtools without issue until just recently. Now i am getting this error.

![image](https://user-images.githubusercontent.com/67655701/131923949-9facf1d7-69b0-4289-80f0-c82bbaa13d9a.png)

here are my relevant dependancies
 "@hookform/resolvers": "^2.6.1",
"react": "^16.14.0",
"react-dom": "^16.14.0",
"react-hook-form": "~7.12.1",
"@hookform/devtools": "~3.0.2",

any suggestions as to what might be a solution would be greatly appreciated. If i remove the devtools this error goes away, so im semi confident this is a devTool issue

**Comment by bluebill1049** [comment]
can you reproduce this in a codesandbox?

**Comment by mkoehlerJjk** [comment]
sorry for not getting back sooner, no i just tried with the same imports I have locally, and its only breaking locally, but not in codesandbox
