### ISSUE TITLE
errorMessage.trim() is not a function

### ISSUE THREAD

**Issue by Luc9802** [react-hook-form/devtools#106]
Disclaimer: I'm using react-hook-form v5 and react-hook-form-devtools v1 but I think this issue could be still present.

I've got the exception reported in the issue title because what I put as errorMessage is an object and not directly a string.
I do such a thing because I'm using yup validation library and I'm setting default error messages as they suggest as objects in order to include a value to replace in the final error string.

https://github.com/jquense/yup#using-a-custom-locale-dictionary
![image](https://user-images.githubusercontent.com/71693205/133052258-d52ccc6f-a222-4300-af98-3ddce0e90365.png)

This works perfectly except the devtool. 
Something like replacing this 
https://github.com/react-hook-form/devtools/blob/c6ce9453b5ac32d4a6dc2cd2e41b9eaf4133f2b4/src/panelTable.tsx#L216
with 
```js
typeof errorMessage === 'string' ? errorMessage.trim() : JSON.stringify(errorMessage))
```
could probably be effective.

**Comment by rbideau** [comment]
Still present with react-hook-form@7.27.1 and @hookform/devtools@4.0.2

**Comment by bluebill1049** [comment]
would like to send a pr?

**Comment by rbideau** [comment]
I just did !
