### ISSUE TITLE
DevTools always displays and animates to offscreen even if isVisible === false

### ISSUE THREAD

**Issue by jprosevear** [react-hook-form/devtools#113]
I believe because of:
https://github.com/react-hook-form/devtools/blame/1b9891c8f78622e9bb9dff60c5f65d69ac069b70/src/devToolUI.tsx#L29

If the DevTools is not set to be visible visible it will still show itself and transition off the screen

This is actually causing a weird issue with a login form and autofill on chrome because of focus I believe

**Comment by bluebill1049** [comment]
would you like to send us a PR?

**Comment by jprosevear** [comment]
Depends how you want it fixed - removing the animation entirely should trivially fix it, otherwise need to figure out some sort of extra state handling to detect !isVisible and wasVisible or something.  Ideas?

**Comment by jprosevear** [comment]
Opened #114

**Comment by bluebill1049** [comment]
sorry for the late reply. i miss the notification. will take a look at the PR.

**Comment by johnschult** [comment]
Am I missing something, is there a property called `isVisible` that controls whether or not it is open on load? I would love the dev tool to be closed on load.

**Comment by bluebill1049** [comment]
@johnschult would like to send a PR and add that prop?

**Comment by johnschult** [comment]
Yeah I’ll look into it. I just wanted to make sure I wasn’t missing out on something 😄

**Comment by jprosevear** [comment]
Its visible based on local storage (with a default to false)

The issue was when it was not visible it would still start visible and transition off the screen.  My PR fixed that.

**Comment by johnschult** [comment]
Ah ok... figured as much based on the behavior. I was thinking an open property for the component. Thoughts on wether or not that would default to true or false? True would mimic the current behavior without the stored local.
