### ISSUE TITLE
Issue: Form behaviour changes after reseting form.

### ISSUE THREAD

**Issue by SalahAdDin** [react-hook-form/devtools#131]
### Version Number

7.28.0

### Codesandbox/Expo snack

https://codesandbox.io/s/pensive-babbage-bevpx3

### Steps to reproduce

1. Change the Country's field value to check the extra fields are being rendered correctly.
2. Fulfil the form in proper way.
3. Submit the form and check all fields were cleaned/reseted.
4. Change the Country's field value and check the extra fields are not being replaced by others.

### Expected behaviour

After submitting the form, it should re-render the extra fields as it was doing it before to submitting the form.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Closed as a duplicate of #107
