### ISSUE TITLE
Cannot read properties of null (reading 'control')

### ISSUE THREAD

**Issue by panfiva** [react-hook-form/devtools#133]
I am getting an error when adding the following component inside a form:

```tsx
const TestInsideForm = () => {
	const methods = useFormContext()
	console.log(methods)
	return <DevTool />
}
```
Notice that my console.log statement shows that form context is present; however DevTools shows no context present

![image](https://user-images.githubusercontent.com/48455289/169885383-b37c4a34-18c6-4163-ac48-98e18e940be3.png)

![image](https://user-images.githubusercontent.com/48455289/169885128-595b41ea-8976-4885-8dd4-62c2cb3c255b.png)

I use yarn 3.2.0

I noticed that hard-codes `react-hook-form: "7.13.0"`  as DevDependency; however mine react-hook-form version is 7.31.2; could that be an issue?

![image](https://user-images.githubusercontent.com/48455289/169885769-a31ca4a7-ae80-49cf-9a09-bff98f681034.png)

**Comment by panfiva** [comment]
It's possible it is the same issue as https://github.com/react-hook-form/react-hook-form/discussions/5150

**Comment by bluebill1049** [comment]
This is due to Context, please double check, if this still persists post a question in github discussion with a Codesandbox.
