### ISSUE TITLE
Chrome Extension Support

### ISSUE THREAD

**Issue by jsun969** [react-hook-form/devtools#148]
Issue: react-hook-form/react-hook-form#8624
Pull request: react-hook-form/react-hook-form#8628

## Usage
If you have chrome extension. The component won't be displayed and extension will replace the component instead.

**Comment by jsun969** [comment]
I assume we need to implement react-hook-form/devtools-extension#3 here too

**Comment by jsun969** [comment]
Bad news 😭 #153

**Comment by bluebill1049** [comment]
thanks for the update. I have replied there.
