### ISSUE TITLE
`control._names.mount` is undefined in example

### ISSUE THREAD

**Issue by jsun969** [react-hook-form/devtools#153]
Browser error:

![image](https://user-images.githubusercontent.com/29330847/178106828-e5e75336-fc25-4a81-aff8-a065e6580b5f.png)
![image](https://user-images.githubusercontent.com/29330847/178106839-6bcac481-2378-4fa2-a3f3-c3f587ba9053.png)

Editor error:
![image](https://user-images.githubusercontent.com/29330847/178109898-7e6896dd-d6fa-48f3-9449-ffeb22f2df78.png)

**Comment by jsun969** [comment]
@bluebill1049 Can you help me fix this? 😭

**Comment by bluebill1049** [comment]
@jsun969 could we do that ? `(control?._names?.mount ?? [])`?

**Comment by jsun969** [comment]
> @jsun969 could we do that ? `(control?._names?.mount ?? [])`?

I'll try

**Comment by jsun969** [comment]
> @jsun969 could we do that ? `(control?._names?.mount ?? [])`?

emm.. no
