### ISSUE TITLE
Nextjs form id doesn't match server-rendered HTML

### ISSUE THREAD

**Issue by jsun969** [react-hook-form/devtools#159]
with uuid instead of nanoid, it now says "Error: Text content does not match server-rendered HTML." If I comment out devtools, it works fine.

_Originally posted by @parazit13 in https://github.com/react-hook-form/devtools/issues/157#issuecomment-1182868631_

**Comment by jsun969** [comment]
I fixed it in #162 . And we create a beta release `4.2.2-beta.1`.
Could you help us test in your project @parazit13?

cc @yangricardo

**Comment by parazit13** [comment]
of course, thanks for the patch and heads up about it. I installed `4.2.2` and it works great!! @jsun969 @yangricardo

**Comment by bluebill1049** [comment]
thanks @jsun969 for the patch.
