### ISSUE TITLE
Display form errors in the devtool

### ISSUE THREAD

**Issue by Avataw** [react-hook-form/devtools#166]
So I was debugging my application and it was not properly displaying erros as I was still fiddling with my yup schema.

In order to solve my problems I needed to manually print out my form errors etc and I thought it might be nice to just include that in the devtools? :) 

My proposal is a section underneath the formstate where you can have a look at the errors :)

**Comment by jsun969** [comment]
Could you provide a simple example in codesandbox or show your code to us?

**Comment by Avataw** [comment]
@jsun969 do you mean an example of how I would modify the current `<DevTool />` component? 

Or my specific problem I was having? :)

**Comment by jsun969** [comment]
ye. Plz provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) for your problem :P

**Comment by jsun969** [comment]
Thx for reporting. We temporarily close issue this due lack of information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen it.
