### ISSUE TITLE
devtools v4.3.1 causes error on Next.js but v4.3.0 works fine 

### ISSUE THREAD

**Issue by eunsukimme** [react-hook-form/devtools#195]
Hi 👋 I'm trying to use `@hookform/devtools` with my Next.js project, so I installed latest version(`4.3.1`). My code:
```tsx
// index.tsx
// import others...
import dynamic from 'next/dynamic';
const DevTool = dynamic(() => import('@hookform/devtools').then(module => module.DevTool), {
  ssr: false,
});

export default function Page() {
  const formMethods = useForm<FormType>({ ... });
  // some business logics...

  return (
    <FormProvider {...formMethods}>
      // my form components...
      <DevTool control={formMethods.control} placement="top-right" />
    </FormProvider>
  );
};
```

But it causes error like this:
<img width="763" alt="Screen Shot 2023-03-12 at 11 27 14 PM" src="https://user-images.githubusercontent.com/31213226/224551395-59d0db8f-bde2-47bf-88c6-24b10ee2069f.png">
<img width="1053" alt="Screen Shot 2023-03-12 at 11 28 51 PM" src="https://user-images.githubusercontent.com/31213226/224551397-a2fcf025-536b-4232-b34a-91404f5d70d9.png">

## Workaround
So I just downgraded to `4.3.0` and it works fine. I hope this screenshots to be useful to debug.
Thanks!

**Comment by bluebill1049** [comment]
which version are you using with `react-hook-form`?

**Comment by eunsukimme** [comment]
I'm using `react-hook-form` with version `7.40.0`.
<img width="940" alt="Screen Shot 2023-03-13 at 1 30 29 PM" src="https://user-images.githubusercontent.com/31213226/224608615-37fd187e-93ed-4fe5-8f23-e8e188fc1858.png">

**Comment by bluebill1049** [comment]
could you try the latest?

**Comment by eunsukimme** [comment]
Yes! and I found that latest version(`7.43.5`) of `react-hook-form` works fine with latest version(`4.3.1`) of `@hookform/devtools`. Thanks!
