### ISSUE TITLE
Adding support for React 19

### ISSUE THREAD

**Issue by vasivuk** [react-hook-form/devtools#214]
The current peer dependencies for @hookform/devtools do not include support for React 19, while react-hook-form already does.

`@hookform/devtools/package.json`
```
  "peerDependencies": {
    "react": "^16.8.0 || ^17 || ^18",
```

`react-hook-form/package.json`
```
  "peerDependencies": {
    "react": "^16.8.0 || ^17 || ^18 || ^19"
  },
```

Can we add the support for React 19?

**Comment by nahasco** [comment]
We need a quick fix ASAP
