### ISSUE TITLE
React 19 blockers

### ISSUE THREAD

**Issue by aqeelat** [react-hook-form/devtools#217]
Devtools depends on a couple of deps that do not declare react 19 in their peer deps.

* react-simple-animate: ^3.3.12 (latest: 3.5.2) - (react-dom up to ^18)
* little-state-machine: ^4.1.0 (latest: 4.8.0) - (react up to ^18)

Both of these packages haven't released in a while, and I'm not sure if they're maintained.

Therefore, they will be a blocker in upgrading to react 19. It might be a good idea to either vendor them or replace them.

**Comment by bluebill1049** [comment]
both updated.

**Comment by mauro-ni** [comment]
Hi @bluebill1049, I'm sorry to bother you, I'm working on a react 19 application and I'm using @hookform/devtools 4.3.3. 
I have a problem with little-state-machine & react-simple-animate.

````
❯ yarn                     
➤ YN0000: · Yarn 4.6.0
...
➤ YN0060: │ react is listed by your project with version 19.0.0 (p6c43b), which doesn't satisfy what little-state-machine (via @hookform/devtools) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react-dom is listed by your project with version 19.0.0 (p9228c), which doesn't satisfy what react-simple-animate (via @hookform/devtools) and other dependencies request (but they have non-overlapping ranges!).
...
````

Using `yarn why` command I can see the version of these 2 packages used by @hookform/devtools:

little-state-machine (latest version is 5.0.1, latest 4.x version is 4.8.1)
````
❯ yarn why little-state-machine
├─ @hookform/devtools@npm:4.3.3
│  └─ little-state-machine@npm:4.4.1 (via npm:^4.1.0)
│
└─ @hookform/devtools@npm:4.3.3 [4d2ea]
   └─ little-state-machine@npm:4.4.1 [57c54] (via npm:^4.1.0 [57c54])
````


react-simple-animate (latest version is 3.5.3)
````
❯ yarn why react-simple-animate
├─ @hookform/devtools@npm:4.3.3
│  └─ react-simple-animate@npm:3.4.0 (via npm:^3.3.12)
│
└─ @hookform/devtools@npm:4.3.3 [4d2ea]
   └─ react-simple-animate@npm:3.4.0 [57c54] (via npm:^3.3.12 [57c54])
````

It seems that these two packages haven't been updated.

Many thanks in advance for your check and your help.

Mauro

**Comment by aqeelat** [comment]
@mauro-ni run `yarn dedupe` then `yarn up react-simple-animate -r`

**Comment by aqeelat** [comment]
@mauro-ni or delete hookform packages then install them again.

the issue is that they don’t release a new version because the new react-simple-animate and the other state machine package are still within the semver range.

**Comment by mauro-ni** [comment]
@aqeelat many thanks!
