### ISSUE TITLE
Allow multiple forms/devtool instances

### ISSUE THREAD

**Issue by justrhysism** [react-hook-form/devtools#26]
Working on an app which has many forms—now the DevTool isn't included in the production bundle, we've been able to leave the DevTools in (which really helps the team debug issues). However we do have multiple different form contexts in different parts of the app (a common one is a page with a form, then a modal with another form).

Currently, it's impossible to view multiple forms in the DevTool—as one sits in front of the other, and toggling it open and closed triggers _both_ to open and close.

Either need to allow multiple forms in a single DevTool, or provide a way to toggle multiple.

**Comment by tcneuen** [comment]
Even if there is no way to determine which is particularly active is there a way to switch between them?

**Comment by Odonno** [comment]
I am curious to know why it can't be possible to have a global hookform DevTools that is able to provide context for all active forms in the page at any time, simlilar to what TanStack Query devtools can offer.

I imagine such devtools would require few changes:

* store and consume data provided by each usage of `useForm`
* provide a new `Select` (or combobox) to select which form we want to check in the DevTools UI

That would enable us to do something like that:

```tsx
import { lazy, Suspense } from "react";

const enableDevTools = import.meta.env.DEV && __VITE_MODE__ !== "test";

const TanStackQueryDevtools = enableDevTools
  ? lazy(() =>
      import("@tanstack/react-query-devtools").then((d) => ({
        default: d.ReactQueryDevtools,
      }))
    )
  : () => null;

const HookformDevtools = enableDevTools
  ? lazy(() =>
      import("@hookform/devtools").then((d) => ({
        default: d.DevTool,
      }))
    )
  : () => null;

export const DevTools = () => {
  return (
    <Suspense>
      <TanStackQueryDevtools />
      <HookformDevtools />
    </Suspense>
  );
};

```
