### ISSUE TITLE
ie11 support?

### ISSUE THREAD

**Issue by haripriyaaganesan** [react-hook-form/devtools#32]
Hi,

Thanks for the great library. I've been using it for all my projects, but it does not work on IE11.
Can you add support for this one?

I got a Syntax error in index.js
if (process.env.NODE_ENV === 'production') {
  module.exports = {
    **DevTool: () => null,**
  }

Can this be changed to 
if (process.env.NODE_ENV === 'production') {
    module.exports = {
        DevTool: function DevTool() {
            return null;
        }
    };
} else {
    module.exports = require('./dist/react-hook-form-devtools.js');
}

**Comment by bluebill1049** [comment]
hi @haripriyaaganesan you mean the devtool doesn't work on IE 11?

**Comment by bluebill1049** [comment]
any chance you can provide a real screenshot of the error? happy to invest for a fix.

**Comment by haripriyaaganesan** [comment]
Hi Bill,

On ie11 page appears blank. On the console, I got a syntax error. When
clicked, found => function is to blame :)
Attaching screenshots

**Comment by bluebill1049** [comment]
ok thanks, i will take a look at it, I think u forgot to attach the screenshots.

**Comment by haripriyaaganesan** [comment]
![Screen Shot 2020-06-11 at 9 54 27 AM](https://user-images.githubusercontent.com/699941/84465882-f8260080-ac2c-11ea-880e-6b93af70bd2a.png)
![Screen Shot 2020-06-11 at 9 54 50 AM](https://user-images.githubusercontent.com/699941/84465907-01af6880-ac2d-11ea-8dff-efeb66a07dce.png)

**Comment by bluebill1049** [comment]
👍 will take a look at it after (react hook form) v6 is out.

**Comment by bluebill1049** [comment]
sorry, haven't got to this, maybe we can use chrome for dev purpose?

**Comment by haripriyaaganesan** [comment]
It is a client's requirement that our application has to support ie11 as
well. Since the library has es6 js / => functions, page isn't rendered.

FYI: I'm not trying to use react-dev-tool in ie11. Hope this helps
