### ISSUE TITLE
new build is broken the final publish version

### ISSUE THREAD

**Issue by bluebill1049** [react-hook-form/devtools#36]
I think the problem is due to the `index.js` is missing as part of the publish, we should do what do you have done at main-repo. @kotarella1110

**Comment by etroynov** [comment]
is devtools capable with 6 version?

when i try to use it with 6 version a got a error:
```
react-hook-form-devtools.js:288 Uncaught TypeError: formState.dirtyFields.has is not a function
    at react-hook-form-devtools.js:288
    at Array.map (<anonymous>)
    at Panel (react-hook-form-devtools.js:281)
    at renderWithHooks (react-dom.development.js:16240)
    at updateFunctionComponent (react-dom.development.js:18327)
    at beginWork$1 (react-dom.development.js:20150)
    at HTMLUnknownElement.callCallback (react-dom.development.js:337)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:386)
    at invokeGuardedCallback (react-dom.development.js:441)
    at beginWork$$1 (react-dom.development.js:25737)
```

Hook:
```
const { control, watch } = useForm({
    defaultValues: {
        src: {},
    },
})
```

JSX:
```
<Controller
  control={control}
  name="src"
  render={({ value, onChange, onBlur }) => (
    <Select
      selected={value?.number}
      onChange={onChange}
      onBlur={onBlur}
      options={options}
    />
  )}
/>;
```

If i disable devtools everything works fine.

**Comment by bluebill1049** [comment]
@etroynov are you using 2.0.1?

**Comment by etroynov** [comment]
> @etroynov are you using 2.0.1?

i not available in npm :(

**Comment by etroynov** [comment]
are you maintain:
https://www.npmjs.com/package/react-hook-form-devtools

?

**Comment by etroynov** [comment]
as i suppose the current version is:
https://www.npmjs.com/package/@hookform/devtools ?

if it true, can you deprecate:
https://www.npmjs.com/package/react-hook-form-devtools ?

At the moment, 2 packages are a bit confused, I found the second package only after I checked your profile on npm.

**Comment by bluebill1049** [comment]
sorry @hookform/devtools  should be the one going forwards.
