### ISSUE TITLE
DevTools does not show input value, when using Controller

### ISSUE THREAD

**Issue by pixel-mattp** [react-hook-form/devtools#40]
**Describe the bug**
When using Controller to wrap a third party input component, the field is registered and appears in the DevTools list, however does not show a value.  

**To Reproduce**
[Sanbox Link](https://codesandbox.io/s/funny-napier-h5zxh)

**Expected behavior**
Field value should be visible for these fields in DevTools.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Latest Chrome

**Comment by bluebill1049** [comment]
Thanks @pixel-mattp @kotarella1110 is preparing to release a patch for V2 soon.

**Comment by pixel-mattp** [comment]
That's great.  Superb work on this package - we are switching all our development and forms to React Hook form as it's so good.

**Comment by bluebill1049** [comment]
That's awesome to hear @pixel-mattp sorry about the Devtool, I completely screw it up with V6, didn't prepare well for the V6 release with DevTools. My apology.

**Comment by pixel-mattp** [comment]
No problem.  Some awesome additions to V6!  The useWatch function will be a game changer if it isolates render to the component.  DevTools really useful too!

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/icy-http-s02ln?file=/src/InnerComponent.jsx fixed :)
