### ISSUE TITLE
conflicting peer dependency requirements between @hookform/devtools@2.0.2 and react-hook-form-devtools@1.2.0

### ISSUE THREAD

**Issue by cliffordp** [react-hook-form/devtools#42]
I was using `"react-hook-form": "^5.4.2"` so when I installed this devtools package via `npm install @hookform/devtools -D` which resulted in `"react-hook-form-devtools": "^1.1.3"`, but I saw this message:

> @hookform/devtools@2.0.2 requires a peer of react-hook-form@>=6.0.0 but none is installed. You must install peer dependencies yourself.

I wasn't aware my RHF was outdated so then I updated my package.json, ran install, then I saw this:

> react-hook-form-devtools@1.2.0 requires a peer of react-hook-form@^5.6.1 but none is installed. You must install peer dependencies yourself.

So it looks like those 2 have conflicting peer dependency requirements.

**Comment by bluebill1049** [comment]
for v5, you should keep using `react-hook-form-devtools`

**Comment by cliffordp** [comment]
I'm cool updating to v6 but the mutually-exclusive peerDeps is wrong, isn't it?

**Comment by bluebill1049** [comment]
you mean `@hookform/devtools@2.0.2 requires a peer of react-hook-form@>=6.0.0 but none is installed`? 
v6 need v2 because we having breaking change with form state names.

**Comment by bluebill1049** [comment]
are you still getting that message? that's strange.

**Comment by cliffordp** [comment]
confirmed no longer getting the issue. tyvm for helping.
