### ISSUE TITLE
setValue does not set the value of an object field correctly

### ISSUE THREAD

**Issue by pixel-mattp** [react-hook-form/devtools#44]
**Describe the bug**
When using `setValue` to set the value of a field which is an object (for example field name: `objectField.value`) it does not set the value.  
However, it works if you have a field named `objectField`.

**To Reproduce**

[See CodeSandbox for Demo](https://codesandbox.io/s/autumn-paper-rdg73)

**Expected behavior**
Field value should correctly set the object key value.

**Comment by pixel-mattp** [comment]
I’m not sure it is - on my dev environment, when it submits the data to the endpoint, the values are not included and are null?

See screenshot.  The left is dev tools showing the object format inputs.  Right shows the values submitted to the api.  As you can see, the fields are not populated.

<img width="723" alt="Screenshot 2020-07-15 at 11 48 39" src="https://user-images.githubusercontent.com/14015763/87536583-3893f680-c691-11ea-89b1-f04b3e3b4551.png">

**Comment by bluebill1049** [comment]
<img width="570" alt="Screen Shot 2020-07-15 at 9 04 50 pm" src="https://user-images.githubusercontent.com/10513364/87537960-d530b580-c6de-11ea-9a39-2863df1894b6.png">

https://codesandbox.io/s/romantic-river-f8e6m?file=/src/App.js

works in your CSB above

**Comment by pixel-mattp** [comment]
Hmmmmm... it must be the way I am registering the field.

**Comment by bluebill1049** [comment]
are you unregister any of them?

**Comment by pixel-mattp** [comment]
This is how I am registering that field...

```
useEffect(() => {
    formContext.register({ name: props.name, type: 'custom' }, { ...props.rules });
  }, [formContext.register]);
```

**Comment by bluebill1049** [comment]
looks fine to me.

**Comment by pixel-mattp** [comment]
Doh, it was the way i was sending the values.  Helps if you use lodash correctly to merge objects!  Apologies.  The bug still stands for the DevTools however. 

Thanks for your support.

**Comment by bluebill1049** [comment]
fixed

**Comment by pixel-mattp** [comment]
Superb support as always
