### ISSUE TITLE
getStore error in storybook v6 mdx

### ISSUE THREAD

**Issue by yyynnn** [react-hook-form/devtools#47]
state machine error 

probably some init error, cuz devtool loads ok if pages are switched/re-rendered (while in SPA context)

<img width="811" alt="Снимок экрана 2020-07-28 в 12 01 03" src="https://user-images.githubusercontent.com/13677727/88643513-74d04980-d0ca-11ea-8865-8ac59c20772d.png">

**Comment by bluebill1049** [comment]
can you provide more details on all versions?

**Comment by surfer19** [comment]
same problem.. 

`    "@hookform/devtools": "^2.0.3",
    "@roche/rdcp-design-system": "^0.3.3-dev.321",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@types/styled-components": "^5.1.1",
    "@typescript-eslint/eslint-plugin": "^3.7.1",
    "@typescript-eslint/parser": "^3.7.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.4",
    "husky": "^4.2.5",
    "prettier": "^2.0.5",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-hook-form": "^6.1.1",
    "react-scripts": "3.4.1",
    "styled-components": "^5.1.1",
    "typescript": "^3.9.7"`

**Comment by bluebill1049** [comment]
where is devtool?

**Comment by surfer19** [comment]
sorry here is my code:
I tried to put it also upper but no difference
```
function App(): React.ReactElement {
  const { register, handleSubmit, watch, errors, control } = useForm<Inputs>({
    mode: 'onChange'
  });
  const onSubmit = (data: any) => console.log(data);

  console.log(watch('example')); // watch input value by passing the name of it
  return (
    <div
      style={{
        width: '100%',
        textAlign: 'center',
        maxWidth: '400px',
        margin: 'auto',
        paddingTop: '40px'
      }}
    >
      <form onSubmit={handleSubmit(onSubmit)}>
        <Input name="exampleRequired" ref={register({ required: true })} />
        {errors.exampleRequired && <span>This field is required</span>}
        <input type="submit" />
      </form>
      <DevTool control={control} />
    </div>
  );
}
```

**Comment by bluebill1049** [comment]
can you do a re-install? I think i have fixed this early this morning.

**Comment by surfer19** [comment]
Is it published already? I see latest version "@hookform/devtools": "^2.0.3", that I installed yesterday

**Comment by bluebill1049** [comment]
I think the issue it's due to `little-state-machine`.

**Comment by bluebill1049** [comment]
can you check your node_module which version is your `little-state-machine`?

**Comment by surfer19** [comment]
"little-state-machine": "^3.0.1",

**Comment by bluebill1049** [comment]
I mean inside your node_module folder, 3.1.0 is the one having problem.

**Comment by surfer19** [comment]
```
{
  "name": "little-state-machine",
  "sideEffects": false,
  "version": "3.1.0",
```

**Comment by surfer19** [comment]
you are right

**Comment by surfer19** [comment]
@bluebill1049 Last version where devtools are working for me is:
`@hookform/devtools": "2.0.0"`

**Comment by bluebill1049** [comment]
<img width="442" alt="Screen Shot 2020-07-29 at 6 47 57 pm" src="https://user-images.githubusercontent.com/10513364/88778610-11c6db80-d1cc-11ea-9dd7-5286c1231ea8.png">

are you using LSM? maybe you getting the latest version otherwise it's strange because devtool is only getting latest patch and shouldn't take minor version from there.

try remove the whole node modules and reinstall again, it should fix it.

**Comment by surfer19** [comment]
always when I install 2.0.3 it automaticaly installs me to root folder 3.1.0
```
├─ little-state-machine@3.1.0
...
├─ @hookform/devtools@2.0.3
│  ├─ @emotion/core@^10.0.28
│  ├─ @emotion/styled@^10.0.27
│  ├─ @types/lodash@^4.14.152
│  ├─ little-state-machine@^3.0.1
│  ├─ lodash@^4.17.15
│  └─ react-simple-animate@^3.3.8
```

**Comment by surfer19** [comment]
isnt is because "^" ?
```
├─ @hookform/devtools@2.0.3
│  ├─ little-state-machine@^3.0.1
```

**Comment by surfer19** [comment]
so what I assume happened.. they released new minor version of lsm and thats why its installing use 3.1

**Comment by bluebill1049** [comment]
This is fixed right?

**Comment by bluebill1049** [comment]
sorry forgot to follow up.

**Comment by surfer19** [comment]
Yes its not global issue it happens only for me cause I have abstraction in npm and because there is `^` before little-state-machine it installs wrong version:(. But if you will update package and remove ^ it would be perfect:)

**Comment by bluebill1049** [comment]
I think that issue is patched with little-state-machine as well :) so going to close this issue.

**Comment by surfer19** [comment]
thanks anyway!
