### ISSUE TITLE
devtools v. 2.0.4 not disabled in production build

### ISSUE THREAD

**Issue by kle-dev** [react-hook-form/devtools#49]
can I disable the devtools in production builds automatically or do I have to remove it every time everywhere in code for production ?

**Comment by bluebill1049** [comment]
can you provide more details? what's your env, build and etc...

**Comment by kle-dev** [comment]
Here my dependencies:

```
 "@hookform/devtools": "2.0.4",
    "@material-ui/core": "^4.11.0",
    "@testing-library/jest-dom": "^5.11.3",
    "@testing-library/react": "^10.4.8",
    "@testing-library/user-event": "^12.1.1",
    "babel-plugin-import": "^1.13.0",
    "customize-cra": "^1.0.0",
    "react": "^16.13.1",
    "react-app-rewired": "^2.1.6",
    "react-hook-form": "^6.4.0",
```

build a production build and run in Chrome v. 84.0.4147.125

I created a prod build and dev tools are enabled. wasn't it all time disabled automatically in prod ?

**Comment by bluebill1049** [comment]
looks like it's broken form 2.0.1, @kotarella1110 could you please take a look this?

**Comment by kle-dev** [comment]
@bluebill1049 thanks, thanks for your great work !

**Comment by bluebill1049** [comment]
@kotarella1110 has done amazing to this package as well ❤️

**Comment by bluebill1049** [comment]
looks like it's stopping working from the new build script @kotarella1110

**Comment by bluebill1049** [comment]
here is a quick evidence:
<img width="1662" alt="Screen Shot 2020-08-17 at 10 15 29 am" src="https://user-images.githubusercontent.com/10513364/90347280-9b9ef180-e072-11ea-9d1f-a3c9fcf0946f.png">

**Comment by bluebill1049** [comment]
looks like if there is a module in the package.json, it will pick up that, so i will remove it for now.
