### ISSUE TITLE
latest Devtools throws error w/ latest hook-form

### ISSUE THREAD

**Issue by RileyMShea** [react-hook-form/devtools#51]
# Description

The basic example on the main devtools page [here](https://react-hook-form.com/dev-tools) throws the following error:

`Uncaught TypeError: Cannot read property 'current' of undefined`

The above error occurs in `react-hook-form 6.5.0` but not in the the previous release `6.4.1`.
[Diff between react-hook-form 6.5.0 and 6.4.1](https://github.com/react-hook-form/react-hook-form/compare/v6.4.1...v6.5.0#)

I have observed the error  in development mode on next.js using typescript(tsx) w/ React's `strict mode` enabled.  Have not tested CRA or javascript.

## System

Ubuntu: 20.04
Node: v12
Package Manager: yarn 1.24

## Package Versions
"react":"latest"
"next":"latest"
"typescript":"latest"
"react-hook-form": "6.5.0"
"@hookform/devtools": "2.0.5"

## Error Logs
[localhost-1598190583810.log](https://github.com/react-hook-form/devtools/files/5114029/localhost-1598190583810.log)
[localhost-1598190633960.log](https://github.com/react-hook-form/devtools/files/5114030/localhost-1598190633960.log)

## Screenshots
![image](https://user-images.githubusercontent.com/10238802/90980008-b49e1b80-e526-11ea-9498-df0ef4365fac.png)

**Comment by bluebill1049** [comment]
oh! thanks will get that fixed.

**Comment by bluebill1049** [comment]
could you please help test this beta? `2.1.1-beta.1`

**Comment by Ronny25** [comment]
with version `2.1.1-beta.1` I have another error:
**Cannot read property 'errors' of undefined**

**Comment by Ronny25** [comment]
![Screenshot 2020-08-24 at 15 17 44](https://user-images.githubusercontent.com/15904604/91049144-0628d200-e61d-11ea-86b2-80c69ad390fc.png)

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/winter-cache-b7xey?file=/src/App.tsx

**Comment by bluebill1049** [comment]
Thanks @Ronny25 fixed above :)

**Comment by AuthorProxy** [comment]
I have the same error with new code
