### ISSUE TITLE
DevTools don't show isDirty and isTouched anymore

### ISSUE THREAD

**Issue by levrik** [react-hook-form/devtools#54]
I've just did the upgrade to `react-hook-form` 6.5.1 and 2.2.0 of the dev tools.
But now `isDirty` and `isTouched` isn't shown for fields anymore. Is this change intended?
I'm currently debugging something where seeing this information is crucial.

**Comment by levrik** [comment]
Ah, I figured it out. Looks like I have to read `dirtyFields` and `touched` in my application so they show up in devtools as well. This wasn't required before the upgrade.

**Comment by bluebill1049** [comment]
thanks let's focus on the other ticket.
