### ISSUE TITLE
DevTools show all fields as dirty as soon as a single field is dirty

### ISSUE THREAD

**Issue by levrik** [react-hook-form/devtools#55]
Here a GIF as demo:

![Kapture 2020-08-25 at 07 49 43](https://user-images.githubusercontent.com/9491603/91127973-9875b800-e6a7-11ea-8d2b-6b94f9d1998c.gif)

When manually outputting `dirtyFields` in code, it shows the following:

![image](https://user-images.githubusercontent.com/9491603/91127916-7d0aad00-e6a7-11ea-839e-d3cae1b88e08.png)

So this doesn't seem to be a bug in `react-hook-form` itself since its output is correct.

**Comment by bluebill1049** [comment]
can you share a codesandbox for this issue?

**Comment by levrik** [comment]
@bluebill1049 sorry. didn't see your answer yet. thanks for the quick fix!
