### ISSUE TITLE
Does a babel remove @hookform/devtools plugin exist ?

### ISSUE THREAD

**Issue by Flavien-Pensato** [react-hook-form/devtools#57]
I which remove `@hookform/devtools` from a package dependencie, because a error occur when my app build.

I set `@hookform/devtools` as devDependencies in my package. Should I change it ? If so, my bundle size will still by the same ?

**Comment by bluebill1049** [comment]
This should answer it :) https://bundlephobia.com/result?p=react-hook-form-devtools@1.2.0 (prod build) 👍
