### ISSUE TITLE
Unable to resolve peer dependency with React v17.

### ISSUE THREAD

**Issue by orenklein** [react-hook-form/devtools#67]
Installing the dev tools `npm install @hookform/devtools -D` with the latest version of react (v17.\*.\*) is failing.

It is caused by `little-state-machine` library version 3.1.4  `peerDependency` which is fixed in `little-state-machine` version 4.\*.\*
(Same as react-hook-form/react-hook-form#3284)

    npm ERR! Could not resolve dependency:
    npm ERR! peer react@"^16.8.0" from little-state-machine@3.1.4
    npm ERR! node_modules/@hookform/devtools/node_modules/little-state-machine
    npm ERR!   little-state-machine@"^3.0.1" from @hookform/devtools@2.2.1
    npm ERR!   node_modules/@hookform/devtools
    npm ERR!     dev @hookform/devtools@"*" from the root project

**Comment by bluebill1049** [comment]
please provide a reproducible repo.

**Comment by amankkg** [comment]
@bluebill1049 not sure if there is a need in reproduction repo since this errors occurs only on peerDeps version range mismatch when installing using `npm@7+`

So, I also would like to see React version range to include 17, since there are no breaking changes AFAIK

**Comment by orenklein** [comment]
Not sure how to provide a reproducible repo since it is occurring when executing `npm install` (which you cannot run by yourself with codesandbox which is using yarn). However, I can provide steps to reproduce (you must have npm installed).

 ## How to reproduce

1. `npx create-react-app my-app --template typescript`
2. `cd my-app`
3. `npm i react-hook-form`
4. `npm i @hookform/devtools`


Line 4 will output:
 ### Error log

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"*" from @testing-library/react@11.2.6
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^11.2.6" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"*" from @testing-library/react@11.2.6
npm ERR!     node_modules/@testing-library/react
npm ERR!       @testing-library/react@"^11.2.6" from the root project
npm ERR!     react-dom@"^17.0.2" from the root project
npm ERR!     1 more (@hookform/devtools)
npm ERR!   7 more (react-hook-form, react-scripts, the root project, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-simple-animate@3.3.11
npm ERR! node_modules/@hookform/devtools/node_modules/react-simple-animate
npm ERR!   react-simple-animate@"^3.3.8" from @hookform/devtools@3.0.2
npm ERR!   node_modules/@hookform/devtools
npm ERR!     @hookform/devtools@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

It will occur in any project with react version > 17

As mentioned in the last lines of the error log, you can `Fix the upstream dependency conflict` by running the command with `--legacy-peer-deps`, though it is not advised.

 ## Solution
Now that `little-state-machine` is v4, the cause for the dependency resolve error is `react-simple-animate`.
Changing the peer dependency as in https://github.com/react-hook-form/react-hook-form/commit/a564ec1a8a31ef9a5ac342f423518a30dab800ba should solve this issue.

**Comment by bluebill1049** [comment]
> Not sure how to provide a reproducible repo since it is occurring when executing `npm install` (which you cannot run by yourself with codesandbox which is using yarn). However, I can provide steps to reproduce (you must have npm installed).
> 
> ## How to reproduce
> 1. `npx create-react-app my-app --template typescript`
> 2. `cd my-app`
> 3. `npm i react-hook-form`
> 4. `npm i @hookform/devtools`
> 
> Line 4 will output:
> 
> ### Error log
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! Found: react@17.0.2
> npm ERR! node_modules/react
> npm ERR!   peer react@"*" from @testing-library/react@11.2.6
> npm ERR!   node_modules/@testing-library/react
> npm ERR!     @testing-library/react@"^11.2.6" from the root project
> npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
> npm ERR!   node_modules/react-dom
> npm ERR!     peer react-dom@"*" from @testing-library/react@11.2.6
> npm ERR!     node_modules/@testing-library/react
> npm ERR!       @testing-library/react@"^11.2.6" from the root project
> npm ERR!     react-dom@"^17.0.2" from the root project
> npm ERR!     1 more (@hookform/devtools)
> npm ERR!   7 more (react-hook-form, react-scripts, the root project, ...)
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.8.0" from react-simple-animate@3.3.11
> npm ERR! node_modules/@hookform/devtools/node_modules/react-simple-animate
> npm ERR!   react-simple-animate@"^3.3.8" from @hookform/devtools@3.0.2
> npm ERR!   node_modules/@hookform/devtools
> npm ERR!     @hookform/devtools@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> ```
> 
> It will occur in any project with react version > 17
> 
> As mentioned in the last lines of the error log, you can `Fix the upstream dependency conflict` by running the command with `--legacy-peer-deps`, though it is not advised.
> 
> ## Solution
> Now that `little-state-machine` is v4, the cause for the dependency resolve error is `react-simple-animate`.
> Changing the peer dependency as in [react-hook-form/react-hook-form@a564ec1](https://github.com/react-hook-form/react-hook-form/commit/a564ec1a8a31ef9a5ac342f423518a30dab800ba) should solve this issue.

want to send us a PR? on the other repo?

**Comment by amankkg** [comment]
@orenklein plz confirm if your issue is resolved, all peer deps are updated
