### ISSUE TITLE
Cannot read property 'control' of null

### ISSUE THREAD

**Issue by llldar** [react-hook-form/devtools#77]
I added this to my component exactly like the tutorial and it crashed with message:
Cannot read property 'control' of null

<img width="604" alt="Screenshot 2021-04-11 at 8 47 54 PM" src="https://user-images.githubusercontent.com/9290574/114304717-4c2c9a80-9b07-11eb-99c5-f174f06db3bf.png">

"react": "17.0.1"
"react-hook-form": "7.0.4"
"@hookform/devtools": "3.0.0-rc.2"

**Comment by bluebill1049** [comment]
can you provide more detail and reproducible codesandbox?

**Comment by bluebill1049** [comment]
or at least share some code.

**Comment by llldar** [comment]
sure, I'll add them later

**Comment by llldar** [comment]
https://github.com/llldar/vlepo/blob/253f57a69112aea5855af8eebe0e6bd758d1349d/packages/vlepo-client/src/components/Modals/CreatePostModal/index.tsx#L171

**Comment by llldar** [comment]
I couldn't figure out how to reproduce yet, I'll add sandbox when I do.

**Comment by llldar** [comment]
Sorry looks likes it my enviroment's problem, I nuked all node_modules and this problem is gone.

**Comment by llldar** [comment]
It still exists😅, I'll take a look tomorrow, today my head is a little dizzy.

**Comment by llldar** [comment]
<img width="696" alt="Screenshot 2021-04-11 at 10 39 48 PM" src="https://user-images.githubusercontent.com/9290574/114308507-e0522e00-9b16-11eb-931b-ea58d6541601.png">
Looks like the methods is null, which means useFormContext() returns null. I'm not sure what useFormContext does

**Comment by boazhoch** [comment]
@llldar Same here

**Comment by kutnickclose** [comment]
Pretty sure this is https://github.com/react-hook-form/devtools/issues/73 and can be solved by upgrading to v3.0.2.

**Comment by TheBox193** [comment]
Looks like you must be using `<FormProvider {...methods} >` from  [useFormContext](https://react-hook-form.com/api/useformcontext/) for the Dev tools to load & not error.

**Comment by Tinsulate** [comment]
upgrading to 3.0.2 didn't seem to work for me, but caused another issue.
