### ISSUE TITLE
Whitespace text node error

### ISSUE THREAD

**Issue by pzi** [react-hook-form/devtools#8]
Heya,

I have a field that conditionally is shown on a page (when a checkbox is clicked) and it's value gets set and reset occasionally. When I reset the field and hide it, the following error crops up in the console:

`Whitespace text nodes cannot appear as a child of <tbody>. Make sure you don't have any extra whitespace between tags on each line of your source code.`

Unsure what exactly causes it without having had a look at the source. Just thought I'd raise it in case it rings any bells?

**Comment by bluebill1049** [comment]
oh this could due to prettier... i think i even seen this one before.

**Comment by cliffordp** [comment]
me too.

> Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <tbody>. Make sure you don't have any extra whitespace between tags on each line of your source code.

If this helps...

![image](https://user-images.githubusercontent.com/1812179/79710019-51a32c00-8289-11ea-92bf-df6edba8a2af.png)

**Comment by bluebill1049** [comment]
Thanks, guys it's due to how prettier format the code (white space) I will spend sometimes this weekend (long overdue)

**Comment by cliffordp** [comment]
Thanks for your quick efforts! This is just noise in development mode so not a huge rush but it was helpful to know it wasn't _my code_ causing the issue :)

**Comment by bluebill1049** [comment]
yea, it's annoying for us at work as well. I will find some time to sort it out.

**Comment by pzi** [comment]
could you just slap `// prettier-ignore` above the offending line and format it the way you need it? would that help?

**Comment by bluebill1049** [comment]
@pzi I think that would probably do it or maybe update prettier will solve the problem too.

**Comment by bluebill1049** [comment]
is everyone still having this issue with latest build?

**Comment by stefanprobst** [comment]
i just ran into this as well:

![rhf-devtools](https://user-images.githubusercontent.com/20753323/97582796-73c6f500-19f6-11eb-9a26-864afde53da8.png)

version: 2.2.1

**Comment by ixartz** [comment]
> i just ran into this as well:
> 
> ![rhf-devtools](https://user-images.githubusercontent.com/20753323/97582796-73c6f500-19f6-11eb-9a26-864afde53da8.png)
> 
> version: 2.2.1

@bluebill1049 It seems that the error is back. I'm also on the latest version (2.2.1) and I got the same error.

**Comment by alejandrosaldarriagaGL** [comment]
Still happening in 3.1.0

**Comment by rtkac** [comment]
Still happening in 4.0.2
