### ISSUE TITLE
TypeError: reactHookForm.useFormState is not a function

### ISSUE THREAD

**Issue by ItayGershman** [react-hook-form/devtools#81]
Hey, after installing @hookform/devtools I encountered into this error: "TypeError: reactHookForm.useFormState is not a function"

This is the error on the website:
   9 | };
  10 | 
  11 | const Header = ({ setVisible, control }: Props) => {
> 12 |   const { isValid } = useFormState({
  13 |     control,
  14 |   });

below is my code:

`
import { DevTool } from "@hookform/devtools"; 
return (
<>
      <form
        onSubmit={handleSubmit(onSubmit)}
        className="h-100 d-flex flex-column"
      >
        <div className={"d-flex flex-wrap flex-row"}>
          {inputs.map((input) => {
            return (
              <div style={{ marginRight: 35 }}>
                <CustomInput
                  register={register}
                  control={control}
                  error={errors[input.name]}
                  watch={watch}
                  formState={formState}
                  defaultValues={input.defaultValues}
                  setValue={setValue}
                  {...input}
                />
              </div>
            );
          })}
        </div>
        <hr />
        <div className="d-flex justify-content-between">
          <button type="submit" className="btn btn-primary">
            Submit
          </button>
        </div>
      </form>
      <DevTool control={control} />
    </>
);
`

Thanks :)

**Comment by bluebill1049** [comment]
Which version are you using? I mean both react hook form and dev tool, latest version is a made for V7 hook form.

**Comment by yashwant-dangi** [comment]
@bluebill1049 can we use dev-tool with v6, I can not upgrade to v7. For v6, I am getting the above error.

**Comment by bluebill1049** [comment]
> @bluebill1049 can we use dev-tool with v6, I can not upgrade to v7. For v6, I am getting the above error.

I believe u can use with the old version.
