### ISSUE TITLE
resize-feature

### ISSUE THREAD

**Issue by devstojko** [react-hook-form/devtools#82]
Hello guys,

I am using react-hook-form daily on my job on all projects and I found it a little bit difficult to use devtools because of the fixed width. The true benefit of using react-hook-form and devtools is the fact of its simplicity and bundle size.

The resizing issue was open last year, but it's not live yet. So I have decided to contribute and push that feature so we could get it live shortly for everyone.

Branch: [resize-feature](https://github.com/devstojko/devtools/tree/resizer-feature)

Demo: [storybook](https://6096ff148e820000392e3a0a-srtqnzpouq.chromatic.com/?path=/story/devtoolui--default-dev-tool)

In addition to the resizing feature, changes are made for the tracking of each field collapse state to be in sync with expand/collapse button on the global level.

There is an issue with the global expand/collapse button.

If you expand only one field, the global state remains to expand. When you have multiple fields expanded and you want to collapse them all you have to click twice (EXPAND then COLLAPSE).

Besides resizing, I have some ideas about devtools customization (theme). 💯 

Work is still in progress btw. Looking forward to your opinions/suggestions.

**Comment by bluebill1049** [comment]
We have a toggle position feature and I have been sick yet to be released. Will get that done soon.

**Comment by tonyjara** [comment]
Hi! Long variables names like the ones you get working with field array make it specially difficult to work without the resizing feature! So i'm really looking forward for this! Thank you guys!
