### ISSUE TITLE
TypeError: methods is null when using <DevTool>

### ISSUE THREAD

**Issue by nemonemi** [react-hook-form/devtools#87]
**Describe the bug**

After the initial installation of the library and the DevTool, and a simple setup from the docs, this error gets shown:
![image](https://user-images.githubusercontent.com/77624664/121542355-60f2b500-ca08-11eb-88b8-344bb1cec812.png)

With the [TS] V7 I get a different error `getValues is not a function`.
https://codesandbox.io/s/eager-sun-jt4df?file=/package.json:169-177

V7

- [JS](https://codesandbox.io/s/great-paper-deove) Template
- [TS](https://codesandbox.io/s/eager-sun-jt4df) Template

V6

- [JS](https://codesandbox.io/s/mystifying-keller-5jwf5) Template
- [TS](https://codesandbox.io/s/romantic-moon-0chz7) Template

**Expected behavior**
No error should be thrown.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 89
- @hookform/devtools: next
- react-hook-form: 7.8.3

**Comment by bluebill1049** [comment]
<img width="514" alt="Screen Shot 2021-06-11 at 8 53 06 am" src="https://user-images.githubusercontent.com/10513364/121606946-71e80880-ca92-11eb-993e-4dd482270c20.png">
doesn't look like you are using the right version in the csb?

**Comment by nemonemi** [comment]
The version was the problem in both situations csb and local.
When following the instructions, it direct to installing the "next" version, which, for me installed a release candidate.
![image](https://user-images.githubusercontent.com/77624664/121642394-becadf80-ca90-11eb-9723-d5c425599c5b.png)

Once I've installed the latest 3.1.0, things started working.

Perhaps it would make sense correcting the documentation to be more precise, which will not lead to this kind of errors.
